# Generated by Django 5.1.6 on 2025-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Restaurant Name')),
                ('website', models.URLField(default='', verbose_name='Restaurant Website')),
                ('date_opened', models.DateField(verbose_name='Restaurant Open Date')),
                ('latitude', models.FloatField(verbose_name='Restaurant Latitude')),
                ('longitude', models.FloatField(verbose_name='Restaurant Longitude')),
            ],
        ),
    ]
